- name: Push to Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "wilsonnilus@gmail.com"
          git config --global user.name "wilsonnilus"
          
          # مسح أي ريموت قديم وإضافة الجديد بالبيانات الصحيحة
          git remote remove hf || true
          git remote add hf https://wilsonnilus:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/wilsonnilus/Practitioners-Workload-DB
          
          # الرفع بقوة (Force)
          git push --force hf main
